# Generated by Django 4.1.4 on 2023-01-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='contact_no',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
