# Generated by Django 4.1.4 on 2023-01-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0002_login_address_login_age_login_contact_no_login_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='qualification',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
